name: 'Linear issue'
description: 'Get branch name and extract issue ID'
inputs:
  branch_name:
    description: 'Branch name'
    required: true
    default: 'SWE'
  linear_api_key:
    description: 'Linear api key'
    required: false
    default: ''
outputs:
  issue_id:
    description: 'Issue ID from the branch name'
runs:
  using: 'node16'
  main: 'index.js'