name: 'Linear issue'
description: 'Extract issue ID from the branch name and query Linear issue'
inputs:
  token:
    description: 'GitHub token'
    required: true
    default: ''
  branch_name:
    description: 'Branch name'
    required: true
    default: 'SWE'
  linear_auth_type:
    description: 'Linear authentication type'
    required: false
    default: ''
  linear_auth_key:
    description: 'Linear authentication key'
    required: false
    default: ''
outputs:
  issue_id:
    description: 'Issue ID from the branch name'
runs:
  using: 'node16'
  main: 'index.js'